In [57]:
import pandas as pd
import numpy as np
import yfinance as yf
import datetime as dt
from pandas_datareader import data as pdr

In [58]:
yf.pdr_override()

In [59]:
stock=input("Select stock: ")

Select stock: ccl

In [60]:
startyear=2021
startmonth=1
startday=1

start=dt.datetime(startyear,startmonth,startday)
now=dt.datetime.now()

df=pdr.get_data_yahoo(stock, start, now)

[*********************100%***********************]  1 of 1 completed

In [61]:
df

                 Open       High        Low      Close  Adj Close    Volume
Date
2020-12-31  21.620001  21.790001  20.900000  21.660000  21.660000  25679300
2021-01-04  21.700001  21.709999  20.040001  20.379999  20.379999  40642500
2021-01-05  20.180000  20.850000  20.150000  20.600000  20.600000  32464400
2021-01-06  20.540001  20.920000  20.160000  20.400000  20.400000  35295900
2021-01-07  20.480000  21.280001  20.469999  20.740000  20.740000  28989000
...               ...        ...        ...        ...        ...       ...
2021-07-19  19.719999  20.299999  19.190001  19.719999  19.719999  85011700
2021-07-20  19.920000  21.379999  19.620001  21.190001  21.190001  68050600
2021-07-21  21.740000  23.360001  21.670000  23.190001  23.190001  76663300
2021-07-22  22.760000  22.879999  22.190001  22.709999  22.709999  40877000
2021-07-23  22.709999  22.799999  21.889999  21.959999  21.959999  32551900

[141 rows x 6 columns]

In [62]:
emasused=[3,5,8,10,12,15,30,35,40,45,50,60]

for x in emasused:
    ema=x
    df["Ema "+str(ema)]=round(df.iloc[:,4].ewm(span=ema,adjust=False).mean(),2)

In [63]:
df

,Open,High,Low,Close,Adj Close,Volume,Ema 3,Ema 5,Ema 8,Ema 10,Ema 12,Ema 15,Ema 30,Ema 35,Ema 40,Ema 45,Ema 50,Ema 60
Date,,,,,,,,,,,,,,,,,,
2020-12-31,21.620001,21.790001,20.900000,21.660000,21.660000,25679300,21.66,21.66,21.66,21.66,21.66,21.66,21.66,21.66,21.66,21.66,21.66,21.66
2021-01-04,21.700001,21.709999,20.040001,20.379999,20.379999,40642500,21.02,21.23,21.38,21.43,21.46,21.50,21.58,21.59,21.60,21.60,21.61,21.62
2021-01-05,20.180000,20.850000,20.150000,20.600000,20.600000,32464400,20.81,21.02,21.20,21.28,21.33,21.39,21.51,21.53,21.55,21.56,21.57,21.58
2021-01-06,20.540001,20.920000,20.160000,20.400000,20.400000,35295900,20.60,20.81,21.02,21.12,21.19,21.26,21.44,21.47,21.49,21.51,21.52,21.55
2021-01-07,20.480000,21.280001,20.469999,20.740000,20.740000,28989000,20.67,20.79,20.96,21.05,21.12,21.20,21.40,21.43,21.46,21.48,21.49,21.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-07-19,19.719999,20.299999,19.190001,19.719999,19.719999,85011700,20.71,21.42,22.24,22.71,23.12,23.66,25.33,25.63,25.86,26.02,26.14,26.27
2021-07-20,19.920000,21.379999,19.620001,21.190001,21.190001,68050600,20.95,21.34,22.01,22.43,22.82,23.35,25.06,25.39,25.63,25.81,25.95,26.10
2021-07-21,21.740000,23.360001,21.670000,23.190001,23.190001,76663300,22.07,21.96,22.27,22.57,22.88,23.33,24.94,25.26,25.51,25.70,25.84,26.01
2021-07-22,22.760000,22.879999,22.190001,22.709999,22.709999,40877000,22.39,22.21,22.37,22.59,22.85,23.26,24.80,25.12,25.37,25.57,25.71,25.90
2021-07-23,22.709999,22.799999,21.889999,21.959999,21.959999,32551900,22.18,22.13,22.28,22.48,22.72,23.09,24.61,24.95,25.21,25.41,25.57,25.77

In [64]:
df=df.iloc[60:]

pos=0
num=0
percentchange=[]
bp=0
sp=0
for i in df.index:
    
    cmin=min(df["Ema 3"][i],df["Ema 5"][i],df["Ema 8"][i],df["Ema 10"][i],df["Ema 12"][i],df["Ema 15"][i])
    cmax=max(df["Ema 30"][i],df["Ema 35"][i],df["Ema 40"][i],df["Ema 45"][i],df["Ema 50"][i],df["Ema 60"][i])
    
    close=df["Adj Close"][i]
    
    if (cmin>cmax):
        print("Red White Blue")
        if(pos==0):
            bp=close
            pos=1
            print("Buying now at"+str(bp))
        
    elif(cmax>cmin):
        print("Blue white Red")
        if(pos==1):
            sp=close
            print("selling now at"+str(sp))
            pc=(sp/bp-1)*100
            percentchange.append(pc)
        
    if(num==df["Adj Close"].count()-1 and pos==1):
        pos=0
        sp=clsoe
        print("selling now at "+str(sp))
        pc=(sp/bc-1)*100
        percentchange.append(pc)
    
num+=1

print(percentchange)

Red White Blue
Buying now at26.649999618530273
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Blue white Red
selling now at25.719999313354492
Blue white Red
selling now at27.329999923706055
Blue white Red
selling now at26.90999984741211
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Blue white Red
selling now at26.520000457763672
Blue white Red
selling now at25.950000762939453
Blue white Red
selling now at26.760000228881836
Blue white Red
selling now at26.270000457763672
Blue white Red
selling now at25.8799991607666
Blue white Red
selling now at24.780000686645508
Blue white Red
selling now at25.1200008392334
Blue white Red
selling now at27.200000762939453
Blue white Red
selling now at27.520000457763672
Blue white Red
selling now at28.0
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Red White Blue
Blue white Red
selling now at28.420000076293945
Blue white Red
selling now at28.18000030517578
Blue white Red
selling now at28.670000076293945
Blue white Red
selling now at28.059999465942383
Blue white Red
selling now at28.149999618530273
Blue white Red
selling now at27.459999084472656
Blue white Red
selling now at28.1299991607666
Blue white Red
selling now at26.149999618530273
Blue white Red
selling now at25.780000686645508
Blue white Red
selling now at26.360000610351562
Blue white Red
selling now at26.360000610351562
Blue white Red
selling now at26.059999465942383
Blue white Red
selling now at25.020000457763672
Blue white Red
selling now at24.079999923706055
Blue white Red
selling now at23.719999313354492
Blue white Red
selling now at24.260000228881836
Blue white Red
selling now at23.860000610351562
Blue white Red
selling now at22.850000381469727
Blue white Red
selling now at22.579999923706055
Blue white Red
selling now at21.950000762939453
Blue white Red
selling now at20.920000076293945
Blue white Red
selling now at19.719999313354492
Blue white Red
selling now at21.190000534057617
Blue white Red
selling now at23.190000534057617
Blue white Red
selling now at22.709999084472656
Blue white Red
selling now at21.959999084472656
[-3.4896822457330723, 2.551595928365291, 0.975610628906165, -0.4878017359377762, -2.626637394411435, 0.41276026989163217, -1.4258880533055684, -2.8893075751801334, -7.016881645973905, -5.74108368179126, 2.063794192427504, 3.2645435335333817, 5.065667545192176, 6.64165284465128, 5.741090838821883, 7.579739162019061, 5.290806257391867, 5.628517904206731, 3.0393976643030562, 5.553469281129941, -1.8761726347355734, -3.264536376502758, -1.0881764064907151, -1.0881764064907151, -2.2138842815504267, -6.116319640144496, -9.643526197415952, -10.994372784675367, -8.968102903786246, -10.469039580168582, -14.258909161178124, -15.272044101622672, -17.636018472296033, -21.50093667638233, -26.003753862559964, -20.487801735937772, -12.983111196995479, -14.784242365684896, -17.598501317788262]

In [65]:
gains=0
ng=0
losses=0
nl=0
totalR=1

for i in percentchange:
    if(i>0):
        gains+=i
        ng+=1
        
    else:
        losses+=i
        nl+=1
        
    totalR=totalR*((i/100+1))
    
totalR=round((totalR-1)*100,2)

In [66]:
if(ng>0):
    avgGain=gains/ng
    maxR=str(max(percentchange))

else:
    avgGain=0
    maxR="Undefined"
    
if(nl>0):
    avgLoss=losses/nl
    maxL=str(min(percentchange))
    ratio=str(-avgGain/avgLoss)
else:
    avgloss=0
    maxL="indefined"
    ratio="infinty"

In [67]:
if(ng>0 or nl>0):
    battingAvg=ng/(ng+nl)
else:
    battingAvg=0

In [68]:
print("Result for"+stock+" going back to "+str(df.index[0])+" sample size "+str(ng+nl)+ " trade")
print("emaused "+str(emasused))
print("Batting avg "+str(battingAvg))
print("Gain/Loss ratio "+ratio)
print("Avg gain "+str(avgGain))
print("Avg Loss "+str(avgLoss))
print("Max Return "+maxR)
print("Min Return "+maxL)
print("Total Return over "+str(ng+nl)+" trades" +str(totalR)+"%")

Result forccl going back to 2021-03-30 00:00:00 sample size 39 trade
emaused [3, 5, 8, 10, 12, 15, 30, 35, 40, 45, 50, 60]
Batting avg 0.3333333333333333
Gain/Loss ratio 0.4485457254262211
Avg gain 4.139126619295381
Avg Loss -9.227881093643827
Max Return 7.579739162019061
Min Return -26.003753862559964
Total Return over 39 trades-87.49%